name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-check-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Setup just
      uses: extractions/setup-just@v3
    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      with:
        enable-cache: true
    - name: Setup environment
      run: |
        just sync
    - name: Lint
      run: |
        just lint
    - name: Unit tests
      run: |
        just test
